package com.keyboardtrembler.www;

public class TextDetailsClass {
	String textForTyping[];
	
	public TextDetailsClass() {
		textForTyping  = new String[500];
		
		
		//.............Text details inserting to String..............
		textForTyping[0]="Bangladesh is a area of natural beauties. It is located in south-east asia. It has many wonderful scenary and culture. It has the lengthiest organic unbroken sea seaside called Cox's Bazar. Teknaf a position located by the side of Naf stream. This also represents the end point of Cox's Bazar seaside. \"saint Martin\" a little island in the northeast part of the Bay of Bengal. The local name of the isle is Narikel Jinjira significance \"Coconut Island\" in Arabic. The isle is house to several vulnerable varieties of turtles, as well as the corals, some of which are found only on this isle.";
		textForTyping[1]="Had dreams. Two of 'em. Both had my father. It's peculiar. I'm older now than he ever was by twenty years. So in a sense he's the younger man.";
		textForTyping[2]="It's always difficult to keep personal prejudice out of a thing like this. And wherever you run into it, prejudice always obscures the truth. I don't really know what the truth is. I don't suppose anybody will ever really know. Nine of us now seem to feel that the defendant is innocent, but we're just gambling on probabilities - we may be wrong. We may be trying to let a guilty man go free, I don't know. Nobody really can. But we have a reasonable doubt, and that's something that's very valuable in our system. No jury can declare a man guilty unless it's sure.";
		textForTyping[3]="Comfortable, Mullet? It seems sadly ironic that it's that tie that's got you into this pickle. Now you just take all the time you want. You can play some music if you like.";
		textForTyping[4]="The fault lies not with the mob, who demands nonsense, but with those who do not know how to produce anything else.";
		textForTyping[5]="All Ninja are men of peace, and must always remain so or lose many of the special powers they have developed. Beyond this, the Ninja are also adept at fieldcraft, infiltrating, and espionage.";
		textForTyping[6]="Every time I think of you I feel shot right through with a bolt of blue. It's no problem of mine but it's a problem I find, living a life that I can't leave behind.";
		textForTyping[7]="The car has stopped. Vinny: \"What have you stopped here for? What's wrong with that space over there?\" Tyrone: \"It's too tight.\" Vinny: \"What are you talking about, tight? You could land a jumbo jet in there!\"";
		textForTyping[8]="Is it really necessary to send that email? The more emails you send, the more work others will have to do to prioritize your requests. How many of the things you're mentioning are important? If you have 10 issues to discuss, break them into two groups and focus on the most important group.";
		textForTyping[9]="I've seen it watching me, that misty thing without a face. It weaves my thoughts, lined them up in black lace. It buries my shape and leaves no trace. Tomorrow I will have no shame, and I will start again.";
		textForTyping[10]="You don't know what's in store, but you know what you're here for. Close your eyes, lay yourself beside me. Hold tight for this ride, we don't need no protection. Come alone, we don't need attention.";
		textForTyping[11]="Yeah, you just take Soupy-Sales to prom 'cause I can think of so many cooler things to do that night. I might pumice my feet, I might go to Bren's Unitarian Church, maybe get hit by a truck full of hot garbage juice, you know? Cause all those things, would be exponentially cooler than going to prom with you.";
		textForTyping[12]="Titanium was discovered in 1790 but not purified until the early 1990s. Moreover, the metal did not become widely used until the second half of the twentieth century. However, titanium now has the accumulated experience of some 50 years of modern industrial practice and design application to support its use.";
		textForTyping[13]="A vector is a quantity that has both magnitude and direction. Recall that a scalar, unlike a vector, has only magnitude and no direction. In mechanics, quantities such as force, velocity, acceleration, and momentum are vectors, and you must consider both their magnitude and direction.";
		textForTyping[14]="But I really believe that there are more good people on this earth than bad people, and the good people watch out for each other and take care of each other.";
		textForTyping[15]="I've never tried to keep a specific person alive before, and it's much more troublesome than I would have believed. But that's probably just because it's you. Ordinary people seem to make it through the day without so many catastrophes.";
		textForTyping[16]="Races are not won in the first corner; however, they are often lost there. It's usually best to run as quick as you can for the first few laps, then settle into a comfortable, consistent pace - all the while ready to take advantage of any opportunity to pass.";
		textForTyping[17]="Good games stay within, but at the outer edge, of the player's regime of competence. That is, they feel doable but challenging. This makes them pleasantly frustrating - a flow state for human beings.";
		textForTyping[18]="Who is Keyser Soze? He is supposed to be Turkish. Some say his father was German. Nobody believed he was real. The greatest trick the Devil ever pulled was convincing the world he didn't exist.";
		textForTyping[19]="It led me by the hand, as if to fill the niches in the memories in my oozing brain fluid. Without even a destination, we kept walking. Disgusting clouds were floating in the sky. I already know what will happen to me the next time I wake up.";
		textForTyping[20]="I came here to protect my son. I didn't come here to see you disguised by your church. I thought that was a shameful ceremony.";
		textForTyping[21]="It was a marvelous night, the sort of night one only experiences when one is young. The sky was so bright, and there were so many stars that, gazing upward, one could not help wondering how so many whimsical wicked people could live under such a sky.";
		textForTyping[22]="Tim and the Princess lounge in the castle garden, laughing together, giving names to the colorful birds. Their mistakes are hidden from each other, tucked away between the folds of time, safe.";
		textForTyping[23]="We can experience nothing but the present moment, live in no other second of time, and to understand this is as close as we can get to eternal life.";
		textForTyping[24]="Don't tell me what's in, don't tell me how to write, don't tell me how to win this fight. It isn't your right, isn't your life, it isn't your right to take the only thing that's mine.";
		textForTyping[25]="So ran the speech. Burdened and sick at heart, he feigned hope in his look, and inwardly contained his anguish. Aeneas, more than any, secretly mourned for them all.";
		textForTyping[26]="Many people limit themselves to leading boring, dull lives by accepting the judgment of others that they are of low intelligence. This is not so. Just because one does not process sensory information and replay it the same way as everyone else does not mean that there is a lack of comprehension or interest.";
		textForTyping[27]="They had taken it all away from him now, they had turned away from him and there was nothing for him now. He was alone and there was nothing for him.";
		textForTyping[28]="Just as there are painters and musicians among the poets, so there are poets and painters among the musicians. They become clearly distinguished from each other in proportion as the \"other artist\" is able to assert himself in their conceptions.";
		textForTyping[29]="If the driver would only slow down, the car would actually go faster. It reminds me of the saying, \"never confuse movement for action.\"";
		textForTyping[30]="There are perhaps twenty regular posters on the forum, and some much larger and uncounted number of lurkers.";
		textForTyping[31]="Still, we will let all this be a thing of the past, though it hurts us, and beat down by constraint the anger that rises inside us. Now I am making an end of my anger. It does not become me, unrelentingly to rage on.";
		textForTyping[32]="A chorus is the high-point of a lyric's energy as well as the music's energy. In the chorus you declare what the song is really about.";
		textForTyping[33]="It's been a long day without you, my friend, and I'll tell you all about it when I see you again. We've come a long way from where we began.";
		textForTyping[34]="Although today dalmatians serve primarily as firehouse mascots, back in the days of horse-drawn carts, they provided a valuable service. Dalmatians and horses get along swimmingly, so the dogs were easily trained to run in front of the carts and help clear a path for the firefighters to get to a fire quickly.";
		textForTyping[35]="Always do your best - your best is going to change from moment to moment; it will be different when you are healthy as opposed to sick. Under any circumstance, simply do your best, and you will avoid self-judgment, self-abuse and regret.";
		textForTyping[36]="The beginner writes just twenty pieces. The professional writes three times what's needed, rewrites, discards, rewrites some more, then finally settles on the twenty which work best for that specific audience.";
		textForTyping[37]="Who has a safety deposit box full of money and six passports and a gun? Who has a bank account number in their hip? I come in here, and the first thing I'm doing is I'm catching the sightlines and looking for an exit.";
		textForTyping[38]="Step out the front door like a ghost into the fog where no one notices the contrast of white on white. And in between the moon and you the angels get a better view of the crumbling difference between wrong and right. I walk in the air between the rain through myself and back again. Where? I don't know.";
		textForTyping[39]="Is it sweeter to exist only in the mind or to exist both in the mind and in reality? Flipping out and wailing on guitars is much sweeter when someone is actually doing it. So when we conceive of the sweetest being ever, we are conceiving of the being that exists both in the mind and in reality.";
		textForTyping[40]="A man on a thousand mile walk has to forget his goal and say to himself every morning, \"Today I'm going to cover twenty-five miles and then rest up and sleep.\"";
		textForTyping[41]="I had considered how the things that never happen are often as much realities to us, in their effects, as those that are accomplished.";
		textForTyping[42]="The old man told us to go back to other parts of the yard, but there was no more real work done that afternoon. Stranded in this mill town railroad yard while the whole world was converging elsewhere, we seemed to be nothing but children playing among heroic men.";
		textForTyping[43]="Blessed is he, who in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children.";
		textForTyping[44]="Just because there are things I don't remember doesn't make my actions meaningless. The world doesn't just disappear when you close your eyes, does it?";
		textForTyping[45]="What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though.";
		textForTyping[46]="When she returns to the forum page, her post is there. It is a way now, approximately, of being at home. The forum has become one of the most consistent places in her life, like a familiar cafe that exists somehow outside of geography and beyond time zones.";
		textForTyping[47]="Messes of men in farmer poverty; not much for monks but we pretend to be. Share a silent meal and a pot of chamomile, gypsies like us should be stamped in solidarity. Hold you in my fond but distant memory while waiting for the Mother Hen to gather me who regretfully wrote.";
		textForTyping[48]="What a lamentable thing it is that men should blame the gods and regard us as the source of their troubles, when it is their own transgressions which bring them suffering that was not their destiny.";
		textForTyping[49]="In the casino, the cardinal rule is to keep them playing and to keep them coming back. The longer they play, the more they lose, and in the end, we get it all. Running a casino is like robbing a bank with no cops around.";
		textForTyping[50]="You can't see the changes we see, we who have been with him for so long. Do you think any of us want to look into his eyes for the next hundred years if he loses you?";
		textForTyping[51]="They say, \"Find a purpose in your life and live it\". But, sometimes, it is only after you have lived that you recognize your life had a purpose, and likely one you never had in mind.";
		textForTyping[52]="A melancholy air can never be the right thing; what you want is a bored air. If you are melancholy, it must be because you want something, there is something in which you have not succeeded. It is showing your inferiority. If you are bored, on the other hand, it is the person who has tried in vain to please you who is inferior.";
		textForTyping[53]="To produce a mighty book, you must choose a mighty theme. No great and enduring volume can ever be written on the flea, though many there be who have tried it.";
		textForTyping[54]="We were sent here for something. And we know that all things work together for good to them that love God, to them who are called according to his purpose.";
		textForTyping[55]="Focus your attention on the Now and tell me what problem you have at this moment. I am not getting any answer because it is impossible to have a problem when your attention is fully in the Now.";
		textForTyping[56]="Translating from one language to another, unless it is from Greek and Latin, the queens of all languages, is like looking at Flemish tapestries from the wrong side, for although the figures are visible, they are covered by threads that obscure them, and cannot be seen with the smoothness and color of the right side.";
		textForTyping[57]="Soon I'll be sixty years old, my daddy got sixty-one. Remember life and then your life becomes a better one. I made a man so happy when I wrote a letter once. I hope my children come and visit, once or twice a month.";
		textForTyping[58]="So ran the speech. Burdened and sick at heart, he feigned hope in his look, and inwardly contained his anguish. Aeneas, more than any, secretly mourned for them all.";
		textForTyping[59]="Braising meats and vegetables means to brown them first in a small amount of fat, then reduce the heat, cover the skillet and simmer the food in a small amount of liquid until done. This technique allows larger pieces of food to cook thoroughly and blends flavors. Braising also gives you a little extra time to prepare other parts of the meal.";
		textForTyping[60]="To be a poet is to have a soul so quick to discern, that no shade of quality escapes it, and so quick to feel, that discernment is but a hand playing with finely-ordered variety on the chords of emotion - a soul in which knowledge passes instantaneously into feeling, and feeling flashes back as a new organ of knowledge.";
		textForTyping[61]="Half the time she did things not simply, not for themselves; but to make people think this or that; perfect idiocy she knew for no one was ever for a second taken in.";
		textForTyping[62]="Let's sort the buyers from the spiers, the needy from the greedy, and those who trust me from the ones who don't, because if you can't see value here today, you're not up here shopping. You're up here shoplifting. Anyone like jewelry?";
		textForTyping[63]="And the mind that has conceived a plan of living must never lose sight of the chaos against which that pattern was conceived. That goes for societies as well as for individuals.";
		textForTyping[64]="Pork and beans are actually cooked in the can. One fairly large piece of pork is placed in the can before cooking. After being heated during processing, it melts down to the size you see in the can, its flavor having permeated the beans.";
		textForTyping[65]="All beauty comes from beautiful blood and a beautiful brain. If the greatnesses are in conjunction in a man or woman it is enough, the fact will prevail through the universe, but the gaggery and gilt of a million years will not prevail. Who troubles himself about his ornaments or fluency is lost.";
		textForTyping[66]="By that point, entire sectors of my cerebral cortex seemed to have shut down altogether. Dizzy, fearing that I would black out, I was frantic to reach the South Summit, where my third bottle was waiting.";
		textForTyping[67]="Well I woke in mid-afternoon cause that's when it all hurts the most. I dream I never know anyone at the party and I'm always the host. If dreams are like movies, then memories are films about ghosts. You can never escape, you can only move south down the coast.";
		textForTyping[68]="But older than me now, more constant, more real, and the fur, and the mouth, and the innocence turned to hair and contentment that hangs in abasement - a woman now standing where once there was only a girl.";
		textForTyping[69]="In 1969 four computers located around the country were in communication with each other through ARPANET. By the mid-1980s, the core of the network was in place, the communications protocols had been determined, and the Internet was live. By the early 1990s the first Internet language (http) was written and the first browser was published. The World Wide Web was born.";
		textForTyping[70]="Daddy's flown across the ocean. Leaving just a memory. A snapshot in the family album. Daddy, what else did you leave for me? Daddy, what'd ya leave behind for me? All in all, it was just a brick in the wall. All in all, it was all just bricks in the wall.";
		textForTyping[71]="What is your obsession with this money? My father died when I was thirteen and I inherited this money. You don't think that every day I wake up and wish I could give it back? That I would give it back in a second if I could have one more day with him? But I can't, and that's my life and I deal with it.";
		textForTyping[72]="You underestimate the power of the Dark Side. If you will not fight, then you will meet your destiny.";
		textForTyping[73]="Stupid human propaganda! The very concept of a superior alien species being felled by something as pathetic as...germs... is sheer fantasy! Do they really believe that could happen?";
		textForTyping[74]="Well, I heard my friends really got in a mess so I'm gonna have to leave Yoda, I guess. But I know that I'll be coming back some day. I'll be playing this part 'til I'm old and gray. The long-term contract that I had to sign says I'll be making these movies till the end of time.";
		textForTyping[75]="How can you say I go about things the wrong way? I am human and I need to be loved just like everybody else does.";
		textForTyping[76]="And though it's always been with me, I must tear down the wall and let it be. All I am, and all that I was ever meant to be, in harmony, shining true and smiling back at all who wait to cross. There is no loss.";
		textForTyping[77]="He is in great fear, not knowing what mighty one may suddenly appear, wielding the Ring, and assailing him with war, seeking to cast him down and take his place. That we should wish to cast him down and have no one in his place is not a thought that occurs to his mind. That we should try to destroy the Ring itself has not yet entered into his darkest dream.";
		textForTyping[78]="Look, I understand too little too late. I realize there are things you say and do you can never take back. But what would you be if you didn't even try? You have to try. So after a lot of thought, I'd like to reconsider. Please, if it's not too late, make it a cheeseburger.";
		textForTyping[79]="You realize that trying to keep your distance from me will not lessen my affection for you. All efforts to save me from you will fail.";
		textForTyping[80]="Was it all put into words, or did both understand that they had the same thing at heart and in their minds, so that there was no need to speak of it aloud, and better not to speak of it?";
		textForTyping[81]="Ever since I was a child, folks have thought they had me pegged, because of the way I am, the way I talk. And they're always wrong.";
		textForTyping[82]="Tears are handy for washing away troubling and sad feelings. But when you grow up, you'll learn that there are things so sad, they can never be washed away by tears. That there are painful memories that should never be washed away. So people who are truly strong laugh when they want to cry. They endure all of the pain and sorrow while laughing with everybody else.";
		textForTyping[83]="Within their world, games afford respect and sustenance and a place to pass the time: outcasts welcome. But much of that world, like the Flea House, is gone, or, like the corporate-run Scrabble clubs and tournaments, bowdlerized.";
		textForTyping[84]="So, the gods don't hand out all their gifts at once, not build and brains and flowing speech to all. One man may fail to impress us with his looks but a god can crown his words with beauty, charm, and men look on with delight when he speaks out. Never faltering, filled with winning self-control, he shines forth at assembly grounds and people gaze at him like a god when he walks through the streets.";
		textForTyping[85]="This is why we're here. Because this little gray rock sells for 20 million dollars a kilo. That's the only reason. This is what pays for the whole party, and it's what pays for your science. Those savages are threatening our whole operation. We're on the brink of war and you're supposed to be finding me a diplomatic solution. So use what you've got, and get me some results.";
		textForTyping[86]="Enjoy this next test. I'm going to go to the surface. It's a beautiful day out. Yesterday I saw a deer. If you solve this next test, maybe I'll let you ride an elevator all the way up to the break room, and I'll tell you about the time I saw a deer again.";
		textForTyping[87]="You, my friend, are a victim of disorganized thinking. You are under the unfortunate impression that just because you run away you have no courage; you're confusing courage with wisdom.";
		textForTyping[88]="And even though the moment passed me by, I still can't turn away. 'Cause all the dreams you never thought you'd lose got tossed along the way. And letters that you never meant to send got lost or thrown away. And now we're grown up orphans that never knew their names. We don't belong to no one; that's a shame. If you could hide inside me, maybe for a while, and I won't tell no one your name.";
		textForTyping[89]="It was as if that great rush of anger had washed me clean, emptied me of hope, and, gazing up at the dark sky spangled with its signs and stars, for the first time, the first, I laid my heart open to the benign indifference of the universe.";
		textForTyping[90]="To think that the affairs of this life always remain in the same state is a vain presumption; indeed they all seem to be perpetually changing and moving in a circular course. Spring is followed by summer, summer by autumn, and autumn by winter, which is again followed by spring, and so time continues its everlasting round. But the life of man is ever racing to its end, swifter than time itself, without hope of renewal, unless in the next that is limitless and infinite.";
		textForTyping[91]="Kid, aku sudah terbang dari satu sisi galaksi ini kepada yang lain, dan aku sudah melihat banyak hal aneh. Tapi aku tidak pernah melihat apa pun untuk membuat saya percaya bahawa ada satu Angkatan mahakuasa mengendalikan segalanya. Ada medan tenaga mistik yang mengendalikan MY takdir.";
		textForTyping[92]="There was a little boy once upon a time who in spite of his young age and small size knew his mind. For every copper penny and clover he would find, he'd make a wish for better days and the end of hard times.";
		textForTyping[93]="Too many times we stand aside and let the waters slip away 'til what we put off 'til tomorrow has now become today. So don't you sit upon the shoreline and say you're satisfied. Choose to chance the rapids and dare to dance the tide.";
		textForTyping[94]="The place to improve the world is first in one's own heart and head and hands, and then to work outward from there. Other people can talk about how to expand the destiny of mankind. I just want to talk about how to fix a motorcycle. I think that what I have to say has more lasting value.";
		textForTyping[95]="By the end of the nineteenth century, nearly all of the major political units of Islam, from Indonesia to northern Nigeria, were under some form of European control. Those that had escaped direct occupation - Iran, the Ottoman Empire, Afghanistan, and Morocco - found their sovereignty restricted by European control of their economies.";
		textForTyping[96]="To feel it so like myself, indeed, so brotherly, made me realize that I'd been happy, and that I was happy still. For all to be accomplished, for me to feel less lonely, all that remained to hope was that on the day of my execution there should be a huge crowd of spectators and that they should greet me with howls of execration.";
		textForTyping[97]="Ever seen the size of one of their molars? They go through bone like it's butter. You gotta have a few pigs though, you need about sixteen. They will go through a body that weighs two hundred pounds in about eight minutes. That means that a single pig can consume two pounds of uncooked flesh every minute... Hence the expression \"greedy as a pig.\"";
		textForTyping[98]="When a man walks into a room, he brings his whole life with him. He has a million reasons for being anywhere. Just ask him. If you listen, he'll tell you how he got there, how he forgot where he was going - then he woke up. If you listen, he'll tell you about the time he thought he was an angel and dreamt of being perfect. And then he'll smile, with wisdom, content that he realized the world isn't perfect. We're flawed because we want so much more. We're ruined because we get these things and wish for what we had.";
		textForTyping[99]="It was one of those days when it's a minute away from snowing and there's this electricity in the air, you can almost hear it. And this bag was, like, dancing with me. Like a little kid begging me to play with it. For fifteen minutes. And that's the day I knew there was this entire life behind things, and this incredibly benevolent force.";
		textForTyping[100]="We have a criminal jury system which is superior to any in the world and it's efficiency is only marred by the difficulty of finding twelve men every day who don't know anything and can't read.";
		textForTyping[101]="Glancing through the 1977 Atlanta Yellow Pages reveals a city that had yet to be transformed by the proliferation of ethnic food: only ninety-two out of approximately fifteen hundred restaurants could be classified as non-American.";
		textForTyping[102]="He ain't in the box because of the joke played on him. He back-sassed a free man. They got their rules. We ain't got nothin' to do with that. Would probably have happened to him sooner or later anyway, a complainer like him. He gotta learn the rules the same as anybody else.";
		textForTyping[103]="Dictionaries are designed to appear authoritative. They're thick, sturdy, and precise, with pages of explanatory material and complex notational schemes that create an aura of august finality. People refer to \"the dictionary\" as if there were just one, divinely inspired, like the Bible, and passed down through the ages.";
		textForTyping[104]="There's no sunshine, this impossible year. Only black days and sky grey and clouds full of fear, and storms full of sorrow that won't disappear. Just typhoons and monsoons, this impossible year. There's no good times, this impossible year. Just a beachfront of bad blood and a coast that's unclear. All the guests at the party, they're so insincere. They just intrude and exclude, this impossible year.";
		textForTyping[105]="Dan, let me tell you something. In this envelope are all the questions that James Snodgrass was asked on Twenty One. The odd thing about this envelope is that he appeared on the show January 13th, if you recall. Yet, he somehow mailed this to himself on January 11th via registered mail.";
		textForTyping[106]="Children are blameless. I have never hurt them. Your boy is in no immediate danger, this I swear to you. But between us, dear, you did conspire to kill the Queen's soldiers. We both know the penalty for that crime. How will poor Dhom get on without his mother? And with his breathing problem?";
		textForTyping[107]="Then Annie got the crazy idea that she could talk me into buying a farm. I'm thirty-six years old, I love my family, I love baseball, and I'm about to become a farmer. And until I heard the Voice, I'd never done a crazy thing in my whole life.";
		textForTyping[108]="The arts are not a way to make a living. They are a very human way of making life more bearable. Practicing an art, no matter how well or badly, is a way to make your soul grow, for heaven's sake. Sing in the shower. Dance to the radio. Tell stories. Write a poem to a friend, even a lousy poem. Do it as well as you possibly can. You will get an enormous reward. You will have created something.";
		textForTyping[109]="Now who knows, that had your twigs been bent in another direction, You Ike, may have been a great violinist. You Billy, a great architect. Sherman a dentist, Junior a dancer. Well it's never too late. Now I have here, a woodcarving set, a leather craft set, a metal craft set, and a Mr. Potato set.";
		textForTyping[110]="A vision I had in my sleep last night - as distinguished from a dream which is mere sorting and cataloging of the day's events by the subconscious. This was a vision, fresh and clear as a mountain stream - the mind revealing itself to itself. In my vision, I was on the veranda of a vast estate, a palazzo of some fantastic proportion. There seemed to emanate from it a light from within - this gleaming radiant marble. I had known this place. I had in fact been born and raised there. This was my first return, a reunion with the deepest wellsprings of my being.";
		textForTyping[111]="Plumbers have everything: Greed, sex, spirituality, white-knuckled chases, shameful propositions, a nun, humor, true love, jaded love, taut action, comedy, a bad guy, a good guy, a hero, spine-tingling suspense, a hot babe, a damsel in distress, and a hollywood ending!";
		textForTyping[112]="We travelled by the Underground as far as Aldersgate; and a short walk took us to Saxe-Coburg Square, the scene of the singular story which we had listened to in the morning. It was a poky, little, shabby-genteel place, where four lines of dingy two-storied brick houses looked out into a small railed-in enclosure, where a lawn of weedy grass and a few clumps of faded laurel bushes made a hard fight against a smoke-laden and uncongenial atmosphere.";
		textForTyping[113]="The inability to envision a certain kind of person doing a certain kind of thing because you've never seen someone who looks like him do it before is not just a vice. It's a luxury. What begins as a failure of the imagination ends as a market inefficiency: when you rule out an entire class of people from doing a job simply by their appearance, you are less likely to find the best person for the job.";
		textForTyping[114]="We use words like honor, code, loyalty. We use these words as the backbone of a life spent defending something. You use them as a punchline. I have neither the time nor the inclination to explain myself to a man who rises and sleeps under the blanket of the very freedom that I provide and then questions the manner in which I provide it. I would rather you just said thank you and went on your way. Otherwise, I suggest you pick up a weapon and stand a post. Either way, I don't give a damn what you think you are entitled to.";
		textForTyping[115]="I could see why some of the boys took him for snobby. He had a quiet way about him, a walk and a talk that just wasn't normal around here. He strolled, like a man in a park without a care or a worry in the world, like he had on an invisible coat that would shield him from this place. Yeah, I think it would be fair to say... I liked Andy from the start.";
		textForTyping[116]="This guy's walkin' down a street when he falls in a hole. The walls are so steep he can't get out. A doctor passes by and the guy shouts up, \"Hey you! Can you help me out?\" The doctor writes him a prescription, throws it down the hole and moves on. Then a priest comes along and the guy shouts up, \"Father, I'm down in this hole; can you help me out?\" The priest writes out a prayer, throws it down in the hole and moves on. Then a friend walks by. \"Hey Joe, it's me, can you help me out?\" And the friend jumps in the hole. Our guy says, \"Are ya stupid? Now we're both down here!\" and the friend says, \"Yeah, but I've been down here before, and I know the way out.\"";
		textForTyping[117]="Uh, no, there's more. One time I accidentally drank an entire bottle of vinegar. I thought it was terrible wine. Once, I went out with a guy who wore 3D glasses the entire evening. Oh, one time I rode in a sidecar on a guy's motorcycle, and the sidecar detached and went down a flight of stairs. Another time I went to a really boring movie with a guy, and while I was asleep he tried to pull out one of my teeth. I literally woke up with his hand in my mouth. We went out a couple times after that but then he got weird.";
		textForTyping[118]="And if you're right by me, and I'll guarantee I'll be right by you. But please please don't turn me into a nun. I'm not that kind of girl. I've got a reputation. Around town I'm known as microwave Jane because they say I heat up faster than any micro. And when the fire chief visited - he put up a new code, and made me wear a smoke alarm to my thighs. And the Coast Guard would say I was creating tsunamis in my waterbed. And then the Pope visited and said that I was the only person I've heard that had been on my knees more times than he had. The presidents' filed a restraining order claiming I have a romantic interest in the Washington Monument. Oh you makin' me so vicious. Look at me! Just look at me! Do I look like that type of girl?";
		textForTyping[119]="Most of his visitors, brash emissaries of a new ruling class, barely aware of their own youthful hubris, did not completely grasp the layered meaning of the couplet they had been offered, like a snack to be washed down by a thimble-sized cup of thick, sweet tea. They understood of course that it was a dirge for a fallen empire whose international borders had shrunk to a grimy ghetto circumscribed by the ruined walls of an old city.";
		textForTyping[120]="Whenever life gets you down, Mrs. Brown, and things seem hard or tough, and people are stupid, obnoxious, or daft, and you feel that you've had quite enough, just remember that you're standing on a planet that's he evolving, and revolving at 900 miles an hour. That's orbiting at 90 miles a second, so it's reckoned, a sun that is the source of all our power. The sun and you and me and all the stars that we can see are moving a million miles a day in an outer spiral arm at 40,000 miles an hour in a galaxy we call the Milky Way.";
		textForTyping[121]="I was a son. A brother, like you, a younger brother, and I had an older brother who I loved. Idolized, in fact. And one day I went to him and I begged him to stand with me, and Michael... Michael turned on me. Called me a freak. A monster. And then he beat me down. All because I was different. Because I had a mind of my own.";
		textForTyping[122]="Mitochondria and chloroplasts display similarities with bacteria that led to the endosymbiont theory. This theory states that an early ancestor of eukaryotic cells engulfed an oxygen-using non-photosynthetic prokaryotic cell. Eventually, the engulfed cell formed a relationship with the host cell in which it was enclosed, becoming an endosymbiont, a cell living within another cell. Indeed, over the course of evolution, the host cell and its endosymbiont merged into a single organism, a eukaryotic cell with a mitochondrion. At least one of these cells may have then taken up a photosynthetic prokaryote, becoming the ancestor of eukaryotic cells that contain chloroplasts.";
		textForTyping[123]="Horse hockey! I've seen these dodges for 40 years, all the tricks. Knew a private, pretended he was a mare. Carried a colt in his arm for weeks. Another fellow said he was a daisy. Insisted we water him every morning. No, no, Corporal. It ain't gonna go with me. Now you get out of that froufrou and into a uniform. And you stay in uniform. Dismissed!";
		textForTyping[124]="This story is about Howard Beale who was the news anchorman on UBS TV. In his time, Howard Beale had been a mandarin of television, the grand old man of news, with a HUT rating of 16 and a 28 audience share. In 1969, however, his fortunes began to decline. He fell to a 22 share. The following year, his wife died, and he was left a childless widower with an 8 rating and a 12 share.";
		textForTyping[125]="Do you know how long it takes a working man to save $5,000? Just remember this, Mr. Potter, that this rabble you're talking about... they do most of the working and paying and living and dying in this community. Well, is it too much to have them work and pay and live and die in a couple of decent rooms and a bath? Anyway, my father didn't think so. People were human beings to him. But to you, a warped, frustrated old man, they're cattle. Well in my book, my father died a much richer man than you'll ever be!";
		textForTyping[126]="We generally concur that \"men\" such as a cow, a turkey, a frog, and a fish all possess some spark of consciousness, some kind of primitive \"soul\" but by God, it's a good deal smaller than ours is - and that, no more and no less, is why we \"men\" feel that we have the perfect right to extinguish the dim lights in the heads of these fractionally-souled beasts and to gobble down their once warm and wiggling, now chilled and stilled protoplasm with limitless gusto, and not feel a trace of guilt while doing so.";
		textForTyping[127]="I felt despair. The word's overused and banalified now, despair, but it's a serious word, and I'm using it seriously. For me it denotes a simple admixture - a weird yearning for death combined with a crushing sense of my own smallness and futility that presents as a fear of death.";
		textForTyping[128]="I'm happy here. You know, someone once told me my life is a dream with an anklet attached. If I wake up tomorrow and that anklet is still on, I have a good job, a wonderful home, a partner and a best friend. A family. But to wake up and answer only to myself, that would mean everything.";
		textForTyping[129]="I feel the Aryan in my blood, it's scarier than a blood. Been looking for holy water, now I'm praying for a flood. It feel like time passing me by slower than a slug, while this feeling inside of my body seep in like a drug. Will you hug me, rub me on the back like a child?";
		textForTyping[130]="Hi my name is Jane. We hardly know each other, but that's about to change. Here you're going to get to know a lot about me, and maybe even more than you can imagine. This whole things kinda like a blind date - I mean here you are in your brand new Corvette, running along the superinformation highway. Put your big muscular arm around me and whisper sweet things in my ear. And I'll promise to do whatever your little heart desires. BUT, only you make the right moves. Just imagine watching me get proposition by my sleez bald boss. BUT, if you make the wrong moves. You could turn me into a nun. Imagine that. Me?! A nun? HA! I don't think so. But it's really all up to you. God knows what you'll do with that hot little mouse of yours. Point is: life's a game, and this game is full of life.";
		textForTyping[131]="I am sitting in a room, different from the one you are in now. I am recording the sound of my speaking voice, and I am going to play it back into the room again and again, until the resonant frequencies of the room reinforce themselves, so that any semblance of my speech, with perhaps the exception of rhythm is destroyed. What you will hear then are the natural resonant frequencies of the room articulated by speech. I regard this activity not so much as a demonstration of a physical fact, but more as a way to smooth out any irregularities my speech might have.";
		textForTyping[132]="Knew he was a killer, first time that I saw him. Wonder how many girls he had loved and left haunted. But if he's a ghost then, I can be a phantom, holding him for ransom. Some, some boys are trying too hard, he don't try at all though. Younger than my exes but he act like such a man so. I see nothing better, I keep him forever, like a vendetta.";
		textForTyping[133]="A choice tells the world what is most important to a human being. When a man has a choice to make he chooses what is most important to him, and that choice tells the world what kind of a man he is.";
		textForTyping[134]="Even if there is only one possible unified theory, it is just a set of rules and equations. What is it that breathes fire into the equations and makes a universe for them to describe? The usual approach of science of constructing a mathematical model cannot answer the questions of why there should be a universe for the model to describe. Why does the universe go to all the bother of existing?";
		textForTyping[135]="Few of us make any serious effort to remember what we read. When I read a book, what do I hope will stay with me a year later? If it's a work of nonfiction, the thesis, maybe, if the book has one. A few savory details, perhaps. If it's fiction, the broadest outline of the plot, something about the main characters (at least their names), and an overall critical judgment about the book. Even these are likely to fade. Looking up at my shelves, at the books that have drained so many of my waking hours, is always a dispiriting experience.";
		textForTyping[136]="I think a nerd is a person who uses the telephone to talk to other people about telephones. And a computer nerd therefore is somebody who uses a computer in order to use a computer.";
		textForTyping[137]="A place where there isn't any trouble. Do you suppose there is such a place, Toto? There must be. It's not a place you can get to by a boat or a train. It's far, far away. Behind the moon, beyond the rain...";
		textForTyping[138]="You're worth more dead than alive! Why don't you go to the riffraff you love so much and ask them to let you have $8,000? You know why? Because they'd run you out of town on a rail. But I'll tell you what I'm going to do for you, George. Since the state examiner is still here, as a stockholder of the Building and Loan, I'm going to swear out a warrant for your arrest. Misappropriation of funds, manipulation, malfeasance... All right, George, go ahead! You can't hide in a little town like this!";
		textForTyping[139]="You see, if you shoot pool with some employee here, you can come and borrow money. What does that get us? A discontented, lazy rabble instead of a thrifty working class. And all because a few starry-eyed dreamers like Peter Bailey stir them up and fill their heads with a lot of impossible ideas!";
		textForTyping[140]="His gaze is from the passing of bars so exhausted that it doesn't hold a thing anymore. For him it's as if there were thousands of bars and behind the thousands of bars no world. The sure stride of lithe, powerful steps that around the smallest of circles turns is like a dance of pure energy about a center in which a great will stands numbed. Only occasionally without a sound do the covers of the eyes slide open. An image rushes in, goes through the tensed silence of the frame, only to vanish forever in the heart.";
		textForTyping[141]="One man is dead, another man's life is at stake, if there's a reasonable doubt in your minds as to the guilt of the accused, uh a reasonable doubt, then you must bring me a verdict of \"Not Guilty\". If, however, there's no reasonable doubt, then you must, in good conscience, find the accused \"Guilty\". However you decide, your verdict must be unanimous. In the event that you find the accused \"Guilty\", the bench will not entertain a recommendation for mercy. The death sentence is mandatory in this case. You're faced with a grave responsibility, thank you, gentlemen.";
		textForTyping[142]="I see a little silhouetto of a man. Scaramouche, Scaramouche, will you do the Fandango? Thunderbolt and lightning, very, very fright'ning me. Galileo, Galileo, Galileo, figaro, magnifico. I'm just a poor boy, nobody loves me. He's just a poor boy from a poor family. Spare him his life from this monstrosity.";
		textForTyping[143]="Come as you are, as you were, as I want you to be. As a friend, as a friend, as a known enemy. Take your time, hurry up. The choice is yours, don't be late. Take a rest as a friend, as an old memoria.";
		textForTyping[144]="I've been on a diet every day since I was nineteen, which basically means I've been hungry for a decade. I've had a series of not nice boyfriends, one of whom hit me. Ah, and every time I get my heart broken, the newspapers splash it about as though it's entertainment. And it's taken two rather painful operations to get me looking like this. And, one day not long from now, my looks will go, they will discover I can't act and I will become some sad middle-aged woman who looks a bit like someone who was famous for a while.";
		textForTyping[145]="Finding a way into a criminal organization is about observing social dynamics. You start with a target. You're looking for just the right person to approach. People in the inner circle are usually too tough to go after - anyone with real power is bound to be cautious. Drivers and bodyguards are easier, but they usually don't have real access. You want someone with enough juice to be hungry for more, someone desperate to make a move. In short, you're looking for a frustrated middle manager.";
		textForTyping[146]="Neal was a felon. He was convicted on bond forgery. And as you can see in those files, he was suspected of doing a hell of a lot of other things. Yeah, Neal was a pain in the ass. So did somebody from that past want him dead? Maybe. But he also helped me clear a 93% conviction rate, and that makes enemies too.";
		textForTyping[147]="Wait a minute. Wait a minute, Doc. Ah... Are you telling me that you built a time machine... out of a DeLorean?";
		textForTyping[148]="But... this is what I think. Trying to knock others down a peg just means lowering yourself. Don't go trampling all the hard work and trust you've built up. It insults the effort you put in. The only way that would make you happy is if you were a loser who'd given up on trying. But I don't think that describes you. The Kairu I know hates losing, is curt but kind, and is a hard worker with a strong heart. Because I know how hard you've worked, I'm not really mad. Just very, very sad. Don't act like some filthy adult. You're still young! Don't give up on try-- Kariu: What would you know?! What the hell are you lecturing me for? We're the same age!";
		textForTyping[149]="Triplets born, the throne awaits, a seer warns of a deadly fate. Give up your children, separate. Bide your time Lie in wait! Sonic Underground! Sonic Underground! They made a vow their mother will be found. The children grow - learn what's right. Leaders of the freedom fight They seek their mother. She knows they do. Is it time? If she only knew. Will the prophecy come true? Sonic Underground! Sonic Underground! \"I long for my children but I have to wait. To act too soon could seal their fate.\" They made a vow their mother will be found. Sonic Underground!";
		textForTyping[150]="Llonio said life was a net for luck; to Hevydd the Smith life was a forge; and to Dwyvach the Weaver-Woman a loom. They spoke truly, for it is all of these. But you, Taran said, his eyes meeting the potter's, you have shown me life is one thing more. It is clay to be shaped, as raw clay on a potter's wheel.";
		textForTyping[151]="The fairy Navi awakens Link from a nightmare in which he witnesses a man in black armor pursuing a young girl on horseback. Navi brings Link to the Great Deku Tree, who is cursed and near death. The Deku Tree tells Link a \"wicked man of the desert\" cursed him and seeks to conquer the world, and that Link must stop him. Before dying, the Great Deku Tree gives Link the Spiritual Stone of the Forest and sends him to Hyrule Castle to speak with Hyrule's princess.";
		textForTyping[152]="I'm taking over my body. Back in control, no more shotty. I bet a lot of me was lost. Ts uncrossed and Is undotted. I fought it a lot. And it seems a lot like flesh is all I got. Not anymore, flesh out the door. Swat. I must've forgot, you can't trust me. I'm open a moment and close when you show it. Before you know it, I'm lost at sea. And now that I write and think about it. And the story unfolds.";
		textForTyping[153]="Waiter: What is your name? Aladeen: Allison Burgers. Waiter: That's a made up name. What's your real name? Aladeen: My name is Ladiz. Waiter: Ladiz what? Aladeen: Ladiz Washroom. Waiter: So your name is like the sign. Ladies washroom? That is a made up name, what is your real name? I am interested. We are interested. Aladeen: Emplyes. Waiter: Emplyes what!? Aladeen: Emplyes Mustwashhands. Waiter: That is a made up name. What is your real name. Aladeen: Max. Waiter: Max what? Aladeen: Imumoccupancy120. Waiter: There's a number in the name? WHO ARE YOU!?";
		textForTyping[154]="The year 1997 has arrived. A herd of ugly reds are rushing from the mainland. Crime rate skyrockeded! Hongkong is ruined! Therefore, The Hongkong government called Bruce Lee's relative \"Chin\" for the massacre of the reds. Chin is a killer machine. Wipe out all 1.2 billion of the red communists! However, in mainland China there was a secret project in progress! A project to transform the deceased Tong Shau Ping into an ultimate weapon!";
		textForTyping[155]="I'm a beatbox rocker. And you're dancing to my beat. I'm a beatbox rocker. And you're dancing to my beat. I'm a beatbox rocker. And you're dancing to my beat. I'm a beatbox rocker. And I never sound the same.";
		textForTyping[156]="There is not a liberal America and a conservative America -- there is the United States of America. There is not a Black America and a White America and Latino America and Asian America -- there's the United States of America.";
		textForTyping[157]="I say to you today, my friends, that in spite of the difficulties and frustrations of the moment, I still have a dream. It is a dream deeply rooted in the American dream. I have a dream that one day this nation will rise up and live out the true meaning of its creed: \"We hold these truths to be self-evident: that all men are created equal.\"";
		textForTyping[158]="You have been my friend. That in of itself is a tremendous thing. After all, what's life anyway? We're born, we live a little while, we die. The spider's life can't help being something of a miss. With all this trapping -- and eating flies. By helping you, perhaps I was trying to lift up my own life to trifle.";
		textForTyping[159]="Well, I wanna thank y'all for coming out today, and I wanna thank my supporters from the bottom of my heart. Because we have been tested -- tested by fire. Our border has been put to the test, and let me tell you: we have failed that test. The aliens, the infiltrators, the outsiders, they come right across by light of day or dark of night. They'll bleed us, they're parasites. They'll bleed us until we as a city, a county, a state, a nation are all bled out. Make no mistake: we are at war. Every time an illegal dances across our border it is an act of aggression against this sovereign state, an overt act of terrorism.";
		textForTyping[160]="I have already computed the charge of nursing a beggar's child (in which list I reckon all cottagers, laborers, and four-fifths of the farmers) to be about two shillings per annum, rags included; and I believe no gentleman would repine to give ten shillings for the carcass of a good fat child, which, as I have said, will make four dishes of excellent nutritive meat, when he hath only some particular friend or his own family to dine with him. Thus the squire will learn to be a good landlord, and grow popular among his tenants; the mother will have eight shillings net profit, and be fit for work till she produces another child.";
		textForTyping[161]="The devil found a clever way to infiltrate and bring his manipulation; a slender blonde in a cocktail dress struggling through the intoxication brought on by the gifting of drinks until she was ready to pay back in the bedroom, in the search to appease the demons in her head on a sterile surface in the bathroom.";
		textForTyping[162]="My name is Percy Jackson. I'm twelve years old. Until a few months ago, I was a boarding student at Yancy Academy, a private school for troubled kids in upstate New York. Am I a troubled kid? Yeah. You could say that.";
		textForTyping[163]="The FitnessGram Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.";
		textForTyping[164]="What an astonishing thing a book is. It's a flat object made from a tree with flexible parts on which are imprinted lots of funny dark squiggles. But one glance at it and you're inside the mind of another person, maybe somebody dead for thousands of years. Across the millennia, an author is speaking clearly and silently inside your head, directly to you. Writing is perhaps the greatest of human inventions, binding together people who never knew each other, citizens of distant epochs. Books break the shackles of time. A book is proof that humans are capable of working magic.";
		textForTyping[165]="I'm an apostrophe. I'm just a symbol to remind you that there's more to see. I'm just a product of the system, a catastrophe. And yet a masterpiece, and yet I'm half-diseased.";
		textForTyping[166]="Like a stranger, I am on the outside looking in. I tore myself apart and I am left a skeleton. And it's been a long way down for me. It's been a long way down, but now I'm finally here. I will never understand.";
		textForTyping[167]="Why would a Wookiee, an 8-foot-tall Wookiee, want to live on Endor, with a bunch of 2-foot-tall Ewoks? That does not make sense! But more important, you have to ask yourself: What does this have to do with this case? Nothing. Ladies and gentlemen, it has nothing to do with this case! It does not make sense! Look at me. I'm a lawyer defending a major record company, and I'm talkin' about Chewbacca! Does that make sense? Ladies and gentlemen, I am not making any sense! None of this makes sense! And so you have to remember, when you're in that jury room deliberatin' and conjugatin' the Emancipation Proclamation, does it make sense? No! Ladies and gentlemen of this supposed jury, it does not make sense! If Chewbacca lives on Endor, you must acquit! The defense rests.";
		textForTyping[168]="When I was a child, I heard voices. Some would sing and some would scream. You'll soon find you have few choices. I learned the voices died with me. When I was a child, I'd sit for hours, staring into open flames. Something in it had a power, could barely tear my eyes away. All you have is your fire and the place you need to reach. Don't you ever tame your demons, but always keep them on a leash.";
		textForTyping[169]="Build a man a fire, and he'll be warm for a day. Set a man on fire, and he'll be warm for the rest of his life.";
		textForTyping[170]="Seen about a million roads. I've done the bong to Tokyo. I've been a clone and had a little luck. Swam across the golden sea a certain price of levity. It brings us up and only makes us sleep. Television changing channels telling people wearing flannels. Culture shocking walkways to the shore. Even though I never know and even though I never know. And even though I never want to know.";
		textForTyping[171]="I am assured by our merchants, that a boy or a girl before twelve years old, is no salable commodity, and even when they come to this age, they will not yield above three pounds, or three pounds and half a crown at most, on the exchange; which cannot turn to account either to the parents or kingdom, the charge of nutriments and rags having been at least four times that value.";
		textForTyping[172]="Holmes had sat up upon the couch, and I saw him motion like a man who is in need of air. A maid rushed across and threw open the window. At the same instant I saw him raise his hand and at the signal I tossed my rocket into the room with a cry of \"Fire!\" The word was no sooner out of my mouth than the whole crowd of spectators, well dressed and ill - gentlemen, ostlers, and servant maids - joined in a general shriek of \"Fire!\" Thick clouds of smoke curled through the room and out at the open window.";
		textForTyping[173]="As he spoke the gleam of the sidelights of a carriage came round the curve of the avenue. It was a smart little landau which rattled up to the door of Briony Lodge. As it pulled up, one of the loafing men at the corner dashed forward to open the door in the hope of earning a copper, but was elbowed away by another loafer, who had rushed up with the same intention. A fierce quarrel broke out, which was increased by the two guardsmen, who took sides with one of the loungers, and by the scissors-grinder, who was equally hot upon the other side.";
		textForTyping[174]="Out of another I get a lovely view of the bay and a little private wharf belonging to the estate. There is a beautiful shaded lane that runs down there from the house. I always fancy I see people walking in these numerous paths and arbors, but John has cautioned me not to give way to fancy in the least. He says that with my imaginative power and habit of story-making, a nervous weakness like mine is sure to lead to all manner of excited fancies, and that I ought to use my will and good sense to check the tendency. So I try.";
		textForTyping[175]="I'm not the protagonist of a novel or anything... I'm a college student who likes to read, like you could find anywhere. But... if, for argument's sake, you were to write a story with me in the lead role, it would certainly be... a tragedy.";
		textForTyping[176]="Must the citizen ever for a moment, or in the least degree, resign his conscience to the legislator? Why has every man a conscience then? I think that we should be men first, and subjects afterward. It is not desirable to cultivate a respect for the law, so much as for the right. The only obligation which I have a right to assume is to do at any time what I think right.";
		textForTyping[177]="Honestly, if you could see just what was going on outside your realm of perception, it would blow your minds! That's the main reason I kept it back. If I were to give you an analogy, I'd describe it like this: when a duck swims on the water, you only see it glide, apparently effortlessly across the lake. But underneath, as in beneath the surface, it's a whole different story. Its legs are moving like it's pedaling a bicycle up a mountain! Well, that's me right now. I am that duck!";
		textForTyping[178]="If there really is a complete unified theory that governs everything, it presumably also determines your actions. But it does so in a way that is impossible to calculate for an organism that is as complicated as a human being. The reason we say that humans have free will is because we can't predict what they will do.";
		textForTyping[179]="People's beliefs about their abilities have a profound effect on those abilities. Ability is not a fixed property; there is a huge variability in how you perform. People who have a sense of self-efficacy bounce back from failures; they approach things in terms of how to handle them rather than worrying about what can go wrong.";
		textForTyping[180]="There was but one question he left unasked, and it vibrated between his lines: if gross miscalculations of a person's value could occur on a baseball field, before a live audience of thirty thousand, and a television audience of millions more, what did that say about the measurement of performance in other lines of work? If professional baseball players could be over- or undervalued, who couldn't?";
		textForTyping[181]="The rate of progress is so rapid that what one learns at school or university is always a bit out of date. Only a few people can keep up with the rapidly advancing frontier of knowledge, and they have to devote their whole time to it and specialize in a small area. The rest of the population has little idea of the advances that are being made or the excitement they are generating.";
		textForTyping[182]="Does she know what she's getting, Spock? A carcass full of memory banks who should be squatting on a mushroom? Instead of passing himself off as a man? You belong in the circus, Spock, not a starship. Right next to the dog face boy!";
		textForTyping[183]="I'm a great quitter. It's one of the few things I do well. I come from a long line of quitters. My father was a quitter, my grandfather was a quitter... I was raised to give up.";
		textForTyping[184]="Once upon a time a boy's popularity was based on kickball abilities, pea-shooting range, and how much of the alphabet he could squeeze off with one burp. For the same boy to acquire a comparable level of popularity in junior high school he's gonna need a girl.";
		textForTyping[185]="There's a dark side to each and every human soul. We wish we were Obi-Wan Kenobi, and for the most part we are, but there's a little Darth Vader in all of us. Thing is, this ain't no either/or proposition. We're talking about dialectics, the good and the bad merging into us. You can run but you can't hide. My experience? Face the darkness. Stare it down. Own it. As brother Nietzsche said, being human is a complicated gig. So give that ol' dark night of the soul a hug. Howl the eternal yes!";
		textForTyping[186]="Whatever happened to chivalry? Does it only exist in '80s movies? I want John Cusack holding a boombox outside my window. I wanna ride off on a lawnmower with Patrick Dempsey. I want Jake from \"Sixteen Candles\" waiting outside the church for me. I want Judd Nelson thrusting his fist into the air because he knows he got me. Just once I want my life to be like an '80s movie, preferably one with a really awesome musical number for no apparent reason. But no, no, John Hughes did not direct my life.";
		textForTyping[187]="As I've gotten older, I realize I'm certain of only two things. Days that begin with rowing on a lake are better than days that do not. Second, a man's character is his fate. And as a student of history, I find this hard to refute. For most of us our stories can be written long before we die. There are exceptions among the great men of history, but they are rare, and I am not one of them. I am a teacher - simply that. I taught for 34 years. One day I stopped teaching. Those were the facts of my life's chronicle. The last chapter had been written. My book was closed.";
		textForTyping[188]="So, you gave him a pass, Dr. Sanderson? Perhaps they neglected to tell you at medical school that a rabbit has large pointed ears? Do you know what you've done? You've allowed a psychopathic case to walk out of here and roam around with an overgrown white rabbit! You've laid me open to a lawsuit! I shall have to do something I haven't done for fifteen years! I'll have to go after this man, Dowd, and bring him back! But when I do, Dr. Sanderson, your connection with this institution will have ended - as of that moment!";
		textForTyping[189]="I find I'm so excited, I can barely sit still or hold a thought in my head. I think it's the excitement only a free man can feel, a free man at the start of a long journey whose conclusion is uncertain. I hope I can make it across the border. I hope to see my friend and shake his hand. I hope the Pacific is as blue as it has been in my dreams. I hope.";
		textForTyping[190]="I took a course in art last winter. I learnt the difference between a fine oil painting, and a mechanical thing, like a photograph. The photograph shows only the reality. The painting shows not only the reality, but the dream behind it. It's our dreams, doctor, that carry us on. They separate us from the beasts.";
		textForTyping[191]="Your father's light saber. This is the weapon of a Jedi Knight. Not as clumsy or random as a blaster; an elegant weapon for a more civilized age. For over a thousand generations, the Jedi Knights were the guardians of peace and justice in the Old Republic. Before the dark times... before the Empire.";
		textForTyping[192]="We want to help you, Mr. Valentine. My brother and I run a privately-funded program to rehabilitate culturally disadvantaged people. We'd like to supply you with a home of your own, a car, a generous bank account, and employment with our company.";
		textForTyping[193]="Why, anybody can have a brain. That's a very mediocre commodity. Every pusillanimous creature that crawls on the Earth or slinks through slimy seas has a brain. Back where I come from, we have universities, seats of great learning, where men go to become great thinkers. And when they come out, they think deep thoughts and with no more brains than you have. But they have one thing you haven't got: a diploma.";
		textForTyping[194]="Why shouldn't I work for the NSA? That's a tough one, but I'll take a shot. Say I'm working at NSA. Somebody puts a code on my desk, something nobody else can break. Maybe I take a shot at it and maybe I break it. And I'm real happy with myself, 'cause I did my job well. But maybe that code was the location of some rebel army in North Africa or the Middle East. Once they have that location, they bomb the village where the rebels were hiding and fifteen hundred people I never met, never had no problem with, get killed.";
		textForTyping[195]="We're knights of the Round Table, we dance whene'er we're able. We do routines and chorus scenes with footwork impeccable. We dine well here in Camelot. We eat ham and jam and Spam a lot. We're knights of the Round Table, our shows are formidable. But many times we're given rhymes that are quite unsingable. We're opera mad in Camelot, we sing from the diaphragm a lot. In war we're tough and able, quite indefatigable. Between our quests we sequin vests and impersonate Clark Gable. It's a busy life in Camelot. I have to push the pram a lot.";
		textForTyping[196]="Look, I'm gonna give you your choice. I'm not gonna be biased in any way. Tomorrow night you can either play Goofy Golf, which is a lot of standing in line and shoving and pushing and probably getting a zero, or you can see Pinocchio, which is a lot of furry animals and magic, and you'll have a wonderful time. Okay? Now let's vote.";
		textForTyping[197]="Well, yes. Yes, everything's political. Like everything else, the relationship between a man and a woman has a socioeconomic base. Marriage must be founded on mutual beliefs. A common attitude and philosophy towards society...";
		textForTyping[198]="I was involved, deeply involved, in a deception. I have deceived my friends and I had millions of them. I lied to the American people. I lied about what I knew and then I lied about what I did not know. In a sense I was like a child who refuses to admit a fact in the hope that it would go away. Of course it did not go away. I was scared, scared to death. I had no solid position, no basis to stand on for myself. There was one way out and that was simply to tell the truth.";
		textForTyping[199]="You'll see one day when you move out it just sort of happens one day and it's gone. You feel like you can never get it back. It's like you feel homesick for a place that doesn't even exist. Maybe it's like this rite of passage, you know. You won't ever have this feeling again until you create a new idea of home for yourself, you know, for your kids, for the family you start, it's like a cycle or something. I don't know but I miss the idea of it, you know. Maybe that's all family really is. A group of people that miss the same imaginary place.";
	
	}
	
	//....................................
//	public static void main(String[] args) {
//		TextDetailsClass a = new TextDetailsClass();
////		System.out.println(a.textForTyping[26]);
//		
//		int total =0;
//		for(int i=0; i<200; i++)
//		{
//			int len = a.textForTyping[i].length();
//			total+=len;
//			System.out.println(i+". Length = "+len);
//			if(a.textForTyping[i].charAt(0)==' ' || a.textForTyping[i].charAt(len-1)==' ')
//				System.out.println("Have space");
//			if(len>820)
//				System.out.println("****************************************");
//		}
//		System.out.println("Total: "+total);
//		
////		for(int i=150; i<200; i++)
////		{
////			System.out.println("textForTyping["+i+"]=\"\";");
////		}
//	}
}
